name: Telegram Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_CHAT_ID: "-1001964570396"
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
          USER: ${{ github.actor }}
          AUTHOR_URL: https://github.com/${{ github.actor }}
          COMMITS_JSON: ${{ toJson(github.event.commits) }}
        run: |
          MESSAGE="*New Commit Pushed*\n\n"
          MESSAGE+="*Commit by:* [${USER}](${AUTHOR_URL})\n"
          MESSAGE+="*Repository:* ${REPO}\n"
          MESSAGE+="*Branch:* ${BRANCH_NAME}\n\n"

          mapfile -t COMMITS < <(echo "$COMMITS_JSON" | jq -c '.[]')
          for commit in "${COMMITS[@]}"; do
            HASH=$(jq -r '.id' <<< "$commit")
            FULL_MSG=$(jq -r '.message' <<< "$commit")
            MSG_TITLE=$(echo "$FULL_MSG" | head -n 1)
            MSG_BODY=$(echo "$FULL_MSG" | tail -n +2)
            SHORT_HASH=${HASH:0:7}
            URL="https://github.com/${REPO}/commit/${HASH}"
            MESSAGE+="[${SHORT_HASH}](${URL}): ${MSG_TITLE}\n"
            if [[ -n "$MSG_BODY" ]]; then
              MESSAGE+="${MSG_BODY}\n"
            fi
          done

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -H "Content-Type: application/json" \
          -d '{
            "chat_id": "'"${TELEGRAM_CHAT_ID}"'",
            "text": "'"${MESSAGE//\"/\\\"}"'",
            "parse_mode": "Markdown",
            "disable_web_page_preview": true
          }'